### PR TITLE
Enhancement: Ability to use different README_template.md

### LINKED ISSUE #195: Enhancement: Ability to use different README_template.md
**Summary**
With support for multiple sources (e.g., individuals, conferences/symposium), having the ability to select different README_template.md would be nice. Previously, we would upload such content. A current work around is to include the template as part of the deposit.

**Objectives**
1. For Space Grant, WCCFL, and DVC deposits, we would use an existing pre-defined template that is incorporated in the GitHub repo.

**Proposal**

- [x] ~Changes to the configuration is needed~ (actually this ended up not needing to happen)
- [x] Update `ReadmeClass` for option to select template and use `templates/` path
- [x] Add templates
  - [x] Migrate README_template.md to Main.md
  - [x] Add Space_Grant.md
  - [x] Add WCCFL.md
  - [x] Add DVC.md

Not slated for this feature but later on for improvements
1. Handling based on Qualtrics Deposit Agreement match using `survey_shortname`
2. Add option to not use default based on Qualtrics form

*Testing notes*

*Additional notes*

**Implemented in**: TBD

### PR DESCRIPTION
**Pull request by astrochun**
**Description**

This here incorporates a feature to search a templates folder for all templates and prompts uses to select a template.
It does not have the capability to identify via the Deposit Agreement which one to use (future improvement)

Closes #195

**ToDo List**

**Test plan**

Testing with regular deposit
 - [x] Using Main template
 - [x] Using WCCFL template
 - [x] Using Space Grant template
 - [x] Test with user template README.md

Testing with WCCFL deposit
 - [x] Using WCCFL template
 - [x] Using Main template

Testing with Space Grant deposit:
 - [x] Using Space Grant template
 - [x] Using Main template

Testing with DVD deposit (use published on):
 - [x] Use DVC template

**Update Changelog**

- [x] README.md, [changelog](../../README.md#changelog) 

- [x] Bump version from 1.0.1 to 1.0.2

*Resources*

*Screenshots or additional context*

### CODE REVIEW

**Comment by astrochun** [comment]
Note: For deposits with a README* files present, the template request step happens out of order:
```
13:42:50 -     INFO: ** SELECTING README TEMPLATE **
13:42:50 -     INFO: List of README templates: 
13:42:50 -     INFO:   (0): Space_Grant.md
13:42:50 -     INFO:   (1): Main.md
13:42:50 -     INFO:   (2): WCCFL.md
Select from above list (enter number ONLY) : 2
13:43:22 -     INFO: RESPONSE: 2 == WCCFL.md
13:43:22 -     INFO: 
13:43:22 -     INFO: ** IDENTIFYING README FORM RESPONSE **
13:43:23 -     INFO: Attempting to identify using article_id or curation_id ...
13:43:23 -     INFO: Unique match based on article_id or curation_id !
|    | ResponseId        | SurveyID           |   article_id |   curation_id |
|---:|:------------------|:-------------------|-------------:|--------------:|
| 28 | **** | **** | **** | **** |
13:43:23 -     INFO: Only one entry found!
13:43:23 -     INFO: Survey completed on 2021-3-24 11:57 AM
13:43:23 -     INFO:  ... for ****
13:43:23 -     INFO: Qualtrics README ResponseID : ****
13:43:23 -     INFO: Only one README file found!
13:43:23 -     INFO: PROMPT: Type 'Yes'/'yes' if you wish to use as template.
PROMPT: Anything else will use 'default' : 
13:43:27 -     INFO: RESPONSE: 
13:43:27 -     INFO: Saving default template in DATA ...
```

Thus the checking of readme should always happen before the prompt to select among default templates.

**Review by astrochun — COMMENTED** [review]
Changes look good. There's only one minor change for refactoring the `config_dict['curation']['readme_template']` for simplicity

**Review by damian-romero — APPROVED** [review]
Largest __init__.py file I've seen, but all looks good. I tested it locally and worked fine.

**Comment by astrochun** [comment]
> Largest **init**.py file I've seen, but all looks good. I tested it locally and worked fine.

Yea, it wasn't suppose to be and was intended for easy `import` statement. This will most likely be reorganized.

**Pull request merged**
